### ISSUE TITLE
This already exisits.

### ISSUE THREAD

**Issue by sp1tz** [CosineP/eljs-cli#1]
If you're just trying to run EJS from a terminal, then it's been done:
https://github.com/plasma-umass/ElementaryJS/blob/master/eval/fetchLibs.sh
https://github.com/plasma-umass/ElementaryJS/blob/master/eval/compileAndRun.js

LMK if you have any questions on EJS.

**Comment by CosineP** [comment]
awesome!! thanks for letting me know. i had an old checkout and also couldn't find any documentation for the CLI. i'll edit the readme in a second

if you have time, could you help me with this:
▶ node compileAndRun.js ~/src/220/2.js
EXIT FAILURE on input /home/luna/src/220/2.js: SyntaxError: Unexpected identifier

i got rid of the try-catch and got this:
```
undefined:1
([object Object]({
         ^^^^^^

SyntaxError: Unexpected identifier
    at ElementaryRunner.Object.keys.forEach (/home/luna/src/ElementaryJS/dist/index.js:33:83)
    at Array.forEach (<anonymous>)
    at new ElementaryRunner (/home/luna/src/ElementaryJS/dist/index.js:32:41)
    at Object.compile (/home/luna/src/ElementaryJS/dist/index.js:207:20)
    at Object.<anonymous> (/home/luna/src/ElementaryJS/eval/compileAndRun.js:22:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

if not i'll try to figure it out

**Comment by sp1tz** [comment]
Sure. Well what's your source file (i.e. `~/src/220/2.js`)?

**Comment by CosineP** [comment]
it's my 220 hw (so can't share publicly), but the same exact response for `/tmp/example.js`:

```
function hi() {
    console.log("hi");
}
hi();
```

and `<()`

**Comment by sp1tz** [comment]
I see, you're a 220 student. I'd recommend sticking with Ocelot, since it supports automated backups.

Nonetheless, I can help you later if you really want to get this working on your machine; stepping out for a bit.

**Comment by CosineP** [comment]
weeeell i use git so that's fine, and i wanna use kakoune :}, also i don't want to have google chrome installed. no problem and no pressure, i still have my own script working for now :P, i will try to eventually get this working so i can replace the README with a tutorial on how to use the builtin one

**Comment by sp1tz** [comment]
Alright. I can get things working from scratch on both macOS & Ubuntu. Here's what to do:

1. Clone EJS repo then exec `yarn install && yarn build`.
1. `cd eval/` and run `./fetchLibs.sh`.
1. Update all three libraries (`eval/libs/`) so that `module.epxorts` is set to the top-level function.

For example:
```js
function lib220(config) {
  ...
}
```
now becomes:
```js
module.exports = function lib220(config) {
  ...
};
```
_As an aside you'll probably want to "watch" [this repo](https://github.com/umass-compsci220/ocelot-settings) if you're not using Ocelot._

4. Run your script: `node <relative path to>/compileAndRun.js <script>`.

**Comment by CosineP** [comment]
fantastic, that works, thanks so much for taking the time to help me!! one more question *if you have time*: how do i run the tests?

**Comment by sp1tz** [comment]
Cool. Testing mode isn't (yet) supported. Something like this may work (based on [how Ocelot does it](https://github.com/umass-compsci220/Ocelot/blob/master/frontend/src/sandbox.ts#L114)):
```js
...
      rt = require('../dist/runtime.js'), // Require EJS RT.
      version = require('../dist/version.js'),
...
    throw compilerResult.errors.map(e => `- ${e.message} (line ${e.line})`).join('\n');
  }

  rt.enableTests(true); // Turn on test mode.

  compilerResult.run(result => { 
  // Probably need to tinker with this callback based on test mode or normal mode... 
...
```

**Comment by CosineP** [comment]
but that's exactly.... what this script does `u/u`. okay, i'm gonna continue to use my script, and revert my discontinuation, with a note that for simply running you can use the builtin script. i will keep tabs and archive this repository if testing mode is added. thank you for your patience!!!

**Comment by sp1tz** [comment]
Can you checkout [this branch](https://github.com/plasma-umass/ElementaryJS/tree/test-mode) and try your tests? See `./eval/eval.js`; please LMK how it goes. Thanks.

**Comment by CosineP** [comment]
works like a charm!! thanks so much

**Comment by sp1tz** [comment]
Cool; it's in master now :heavy_check_mark:
